apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: cfae0gy1jm9dsd   # ID 
    url: "http://iot-influxdb:8086"
    isDefault: true
    
    jsonData:
      version: Flux        
      organization: "univaq" 
      defaultBucket: "iot_bucket" 
      httpMode: GET
      tlsSkipVerify: true

    secureJsonData:
      token: "ttq6jLWXxhCl9-fZ2BKm1W18fCJNvPoT4lSo4bP7CxB2IPD6IL0Ohy7EQvyM8qyn9d1iyd9OuHA2QbRn8o_cLA==" 