{
 "title": "iot-maintenance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sector",
    "label": "Settore",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"iot_bucket\", tag: \"sector\")"
    }
   },
   {
    "name": "line",
    "label": "Linea",
    "query": {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"sector\"] == \"${sector}\")\r\n  |> keep(columns: [\"line\"])\r\n  |> distinct(column: \"line\")\r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "engine",
    "label": "Macchinario",
    "query": {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"sector\"] == \"${sector}\")\r\n  |> filter(fn: (r) => r[\"line\"] == \"${line}\")\r\n  |> keep(columns: [\"engine\"])\r\n  |> distinct(column: \"engine\")\r\n  |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SPECIAL ENGINE MONITORING (sector_1/line_1/engine_1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current Absorption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\n  |> filter(fn: (r) => r[\"sector\"] == \"sector_1\")\n  |> filter(fn: (r) => r[\"line\"] == \"line_1\")\n  |> filter(fn: (r) => r[\"engine\"] == \"engine_1\")\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"current\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"value\" then \"Amp\" \n        else if r._field == \"warning_limit\" then \"Warning\" \n        else \"Critical\"\n    })\n  )\n  |> yield(name: \"current\")"
    }
   ]
  },
  {
   "title": "Vibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\n  |> filter(fn: (r) => r[\"sector\"] == \"sector_1\")\n  |> filter(fn: (r) => r[\"line\"] == \"line_1\")\n  |> filter(fn: (r) => r[\"engine\"] == \"engine_1\")\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"vibration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\n  // 1. Convertiamo TUTTO (valore e limiti) in mm/s\n  |> map(fn: (r) => ({ r with _value: r._value * 31.21 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  // 2. Rinominiamo\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"value\" then \"Vib\" \n        else if r._field == \"warning_limit\" then \"Warning\" \n        else \"Critical\"\n    })\n  )\n  |> yield(name: \"vibration\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\n  |> filter(fn: (r) => r[\"sector\"] == \"sector_1\")\n  |> filter(fn: (r) => r[\"line\"] == \"line_1\")\n  |> filter(fn: (r) => r[\"engine\"] == \"engine_1\")\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")\n  // 1. Scarichiamo valore E limiti\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  // 2. Rinominiamo per gli Overrides\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"value\" then \"Temp\" \n        else if r._field == \"warning_limit\" then \"Warning\" \n        else \"Critical\"\n    })\n  )\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "AI Prediction (RUL)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Cycles" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ai_predictions\")\n  |> filter(fn: (r) => r[\"sector\"] == \"sector_1\")\n  |> filter(fn: (r) => r[\"line\"] == \"line_1\")\n  |> filter(fn: (r) => r[\"engine\"] == \"engine_1\")\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"ai_rul\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_threshold\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"RUL\")"
    }
   ]
  },
  { "title": "THERMICAL ANALYTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Temperature Time Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "// 1. Definiamo i target basati sulle variabili della dashboard\ntarget_sector = /^${sector}$/\ntarget_line   = /^${line}$/\ntarget_engine = /^${engine}$/\n\nfrom(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector)\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\n  |> filter(fn: (r) => r[\"engine\"] =~ target_engine)\n  // SELEZIONE SENSORE: Temperatura\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")\n  \n  // 2. Chiediamo sia il valore che i limiti\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\n  \n  // 3. Rinominiamo i campi per renderli leggibili nella legenda\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"value\" then \"Temperatura (°C)\" \n        else if r._field == \"warning_limit\" then \"Warning\" \n        else \"Critical\"\n    })\n  )\n  |> yield(name: \"temperature_data\")"
    }
   ]
  },
  {
   "title": "Temperature Gauges (°C)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ /${sector:regex}/)\r\n  |> filter(fn: (r) => r[\"line\"]   =~ /${line:regex}/)\r\n  |> filter(fn: (r) => r[\"engine\"]  =~ /${engine:regex}/)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  \r\n  // --- LOGICA INTELLIGENTE --\r\n  |> map(fn: (r) => {\r\n      // 1. Prepariamo le versioni corte\r\n      short_s = \"S\" + strings.replaceAll(v: r.sector, t: \"sector_\", u: \"\")\r\n      short_l = \"L\" + strings.replaceAll(v: r.line, t: \"line_\", u: \"\")\r\n      short_e = \"E\" + strings.replaceAll(v: r.engine, t: \"engine_\", u: \"\")\r\n      \r\n      // 2. Componiamo le due stringhe complete\r\n      label_short = short_s + \"/\" + short_l + \"/\" + short_e\r\n      label_long  = r.sector + \"/\" + r.line + \"/\" + r.engine\r\n      \r\n      // 3. IF/ELSE: Se la variabile Grafana è \".*\" (ALL), usa la corta, altrimenti la lunga\r\n      // Nota: usiamo \"${sector}\" con le virgolette per trattarlo come stringa\r\n      final_label = if \"${sector}\" == \".*\" then label_short else label_long\r\n\r\n      // Restituiamo la riga aggiornando il campo \"_field\" con la nostra etichetta dinamica\r\n      return { r with _field: final_label }\r\n  })\r\n\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\r\n  |> yield(name: \"Temp\")"
    }
   ]
  },
  { "title": "ELECTRIC CURRENT ANALYTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Current Absorption Time Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "// 1. Definiamo i target \r\n\r\ntarget_sector = /^${sector}$/\r\ntarget_line   = /^${line}$/\r\ntarget_engine = /^${engine}$/ // InfluxDB mostra \"engine\", non \"asset\"\r\n\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector)\r\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\r\n  |> filter(fn: (r) => r[\"engine\"] =~ target_engine)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"current\")\r\n  \r\n  // 2. Chiediamo sia il valore che i limiti\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"engine\", \"line\", \"sector\"])\r\n  \r\n  // 3. Rinominiamo i campi per renderli leggibili nelle opzioni\r\n  |> map(fn: (r) => ({\r\n      r with \r\n      _field: \r\n        if r._field == \"value\" then \"Corrente (A)\" \r\n        else if r._field == \"warning_limit\" then \"Warning\" \r\n        else \"Critical\"\r\n    })\r\n  )\r\n  |> yield(name: \"data_with_limits\")"
    }
   ]
  },
  {
   "title": "Current Absorption Gauges (Ampere)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"iot_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\n  |> filter(fn: (r) => r[\"sector\"] =~ /${sector:regex}/)\n  |> filter(fn: (r) => r[\"line\"]   =~ /${line:regex}/)\n  |> filter(fn: (r) => r[\"engine\"]  =~ /${engine:regex}/)\n  // FILTRO FONDAMENTALE: Cerchiamo solo la corrente\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"current\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n  // --- INIZIO LOGICA ETICHETTE INTELLIGENTI ---\n  |> map(fn: (r) => {\n      // Creiamo le versioni corte\n      short_s = \"S\" + strings.replaceAll(v: r.sector, t: \"sector_\", u: \"\")\n      short_l = \"L\" + strings.replaceAll(v: r.line, t: \"line_\", u: \"\")\n      short_e = \"E\" + strings.replaceAll(v: r.engine, t: \"engine_\", u: \"\")\n      \n      // Componiamo le due opzioni\n      label_short = short_s + \"/\" + short_l + \"/\" + short_e\n      label_long  = r.sector + \"/\" + r.line + \"/\" + r.engine\n      \n      // Selettore: Se \"sector\" è ALL (.*), usa la corta. Altrimenti la lunga.\n      final_label = if \"${sector}\" == \".*\" then label_short else label_long\n\n      // Sostituiamo il nome del field con la nostra etichetta\n      return { r with _field: final_label }\n  })\n  // ------------------------------------------\n  \n  |> last()\n  // Pulizia finale per evitare che Grafana mostri tag residui\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"]) \n  |> yield(name: \"Current\")"
    }
   ]
  },
  {
   "title": "VIBRATION ANALYTICS (ISO 10816)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }
  },
  {
   "title": "Vibration Time Series (Velocity ISO)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "// 1. Definiamo i Target\r\ntarget_sector = /^${sector}$/\r\ntarget_line   = /^${line}$/\r\ntarget_engine = /^${engine}$/\r\n\r\n// 2. Scarichiamo TUTTI i dati (Valore + Limiti)\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector)\r\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\r\n  |> filter(fn: (r) => r[\"engine\"] =~ target_engine)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"vibration\")\r\n  // Prendiamo valore grezzo E limiti grezzi\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\r\n  // Pulizia tag inutili\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"engine\", \"line\", \"sector\"])\r\n\r\n  // 3. CONVERSIONE E RINOMINA (Tutto x 31.21)\r\n  \r\n  |> map(fn: (r) => ({ r with _value: r._value * 31.21 })) \r\n  |> map(fn: (r) => ({\r\n      r with \r\n      _field: \r\n        if r._field == \"value\" then \"Velocità ISO (mm/s)\" \r\n        else if r._field == \"warning_limit\" then \"Warning\" \r\n        else \"Critical\"\r\n    })\r\n  )\r\n  |> yield(name: \"velocity_only\")"
    }
   ]
  },
  {
   "title": "Vibration Gauges (mm/s)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ /${sector:regex}/)\r\n  |> filter(fn: (r) => r[\"line\"]   =~ /${line:regex}/)\r\n  |> filter(fn: (r) => r[\"engine\"]  =~ /${engine:regex}/)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"vibration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"warning_limit\" or r[\"_field\"] == \"critical_limit\")\r\n  \r\n  // 1. CONVERSIONE (g -> mm/s)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 31.21 }))\r\n\r\n  // 2. Pivot\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  // 3. Etichette Intelligenti\r\n  |> map(fn: (r) => {\r\n      short_s = \"S\" + strings.replaceAll(v: r.sector, t: \"sector_\", u: \"\")\r\n      short_l = \"L\" + strings.replaceAll(v: r.line, t: \"line_\", u: \"\")\r\n      short_e = \"E\" + strings.replaceAll(v: r.engine, t: \"engine_\", u: \"\")\r\n      \r\n      label_short = short_s + \"/\" + short_l + \"/\" + short_e\r\n      label_long  = r.sector + \"/\" + r.line + \"/\" + r.engine\r\n      \r\n      final_label = if \"${sector}\" == \".*\" then label_short else label_long\r\n\r\n      // Restituiamo il valore convertito\r\n      return { r with _field: final_label, _value: r.value }\r\n  })\r\n  \r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\r\n  \r\n  // --- MODIFICA FONDAMENTALE QUI SOTTO ---\r\n  // Raggruppiamo per _field. Questo dice a Grafana: \"Ogni nome diverso è un Gauge diverso\"\r\n  |> group(columns: [\"_field\"]) \r\n  \r\n  |> yield(name: \"Vibration_mm_s\")"
    }
   ]
  }
 ]
}