{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Vibrazione e Accelerazione",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// CONFIGURAZIONE\r\ntarget_asset = \"engine_2\"\r\ntarget_line = \"line_1\"\r\ntarget_sector = \"sector_1\"\r\n\r\n// DATI\r\nbase_data = from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"asset\"] == target_asset)\r\n  |> filter(fn: (r) => r[\"line\"] == target_line)\r\n  |> filter(fn: (r) => r[\"sector\"] == target_sector)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"vibration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\r\n// 1. Accelerazione (g)\r\nbase_data\r\n  |> set(key: \"_field\", value: \"Accelerazione (g)\")\r\n  |> yield(name: \"A\")\r\n\r\n// 2. Velocità (mm/s)\r\nbase_data\r\n  |> map(fn: (r) => ({ r with _value: r._value * 31.21 }))\r\n  |> set(key: \"_field\", value: \"Velocità ISO (mm/s)\")\r\n  |> yield(name: \"V\")"
    }
   ]
  },
  {
   "title": "Assorbimento corrente",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"asset\"] == \"engine_2\")\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> yield(name: \"Corrente\")"
    }
   ]
  },
  {
   "title": "Temperatura motore",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"asset\"] == \"engine_2\")\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> last()"
    }
   ]
  }
 ]
}