{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sector",
    "label": "Settore",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"iot_bucket\", tag: \"sector\")"
    }
   },
   {
    "name": "line",
    "label": "Linea",
    "query": {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"sector\"] == \"${sector}\")\r\n  |> keep(columns: [\"line\"])\r\n  |> distinct(column: \"line\")\r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "asset",
    "label": "Macchinario",
    "query": {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"sector\"] == \"${sector}\")\r\n  |> filter(fn: (r) => r[\"line\"] == \"${line}\")\r\n  |> keep(columns: [\"asset\"])\r\n  |> distinct(column: \"asset\")\r\n  |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vibrazione e Accelerazione",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// CONFIGURAZIONE\r\ntarget_sector = /^${sector}$/\r\ntarget_line   = /^${line}$/\r\ntarget_asset  = /^${asset}$/\r\n\r\n// RECUPERO DATI\r\nbase_data = from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector)\r\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\r\n  |> filter(fn: (r) => r[\"asset\"]  =~ target_asset)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"vibration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"asset\", \"line\", \"sector\"]) \r\n\r\n// 1. Accelerazione (g)\r\nbase_data\r\n  |> set(key: \"_field\", value: \"Accelerazione (g)\")\r\n  |> yield(name: \"A\")\r\n\r\n// 2. Velocità (mm/s)\r\nbase_data\r\n  |> map(fn: (r) => ({ r with _value: r._value * 31.21 }))\r\n  |> set(key: \"_field\", value: \"Velocità ISO (mm/s)\")\r\n  |> yield(name: \"V\")"
    }
   ]
  },
  {
   "title": "Assorbimento corrente",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "// 1. Definiamo i filtri con le REGEX per supportare \"All\"\r\ntarget_sector = /^${sector}$/\r\ntarget_line   = /^${line}$/\r\ntarget_asset  = /^${asset}$/\r\n\r\n// 2. Query\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector) \r\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\r\n  |> filter(fn: (r) => r[\"asset\"]  =~ target_asset)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> set(key: \"_field\", value: \"Corrente (A)\")\r\n  |> yield(name: \"Current\")"
    }
   ]
  },
  {
   "title": "Temperatura motore",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// 1. Definiamo i filtri con le REGEX per supportare \"All\"\r\ntarget_sector = /^${sector}$/\r\ntarget_line   = /^${line}$/\r\ntarget_asset  = /^${asset}$/\r\n\r\n// 2. Query\r\nfrom(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_telemetry\")\r\n  |> filter(fn: (r) => r[\"sector\"] =~ target_sector) \r\n  |> filter(fn: (r) => r[\"line\"]   =~ target_line)\r\n  |> filter(fn: (r) => r[\"asset\"]  =~ target_asset)\r\n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  // Impostiamo il nome pulito per la legenda\r\n  |> set(key: \"_field\", value: \"Temperatura (°C)\")\r\n  \r\n  \r\n  |> last() \r\n  |> yield(name: \"Temp\")"
    }
   ]
  }
 ]
}